qld-gov-au/ckanext-s3filestore

- README.rst
- ckanext/s3filestore/commands.py
- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/uploader.py
- `ckanext.s3filestore.aws_use_ami_role` to make access keys optional
- `ckanext.s3filestore.acl` to change the ACL applied to uploaded files.
bstutsky/ckanext-s3filestore appears to be the cleanest and most up-to-date implementation of these features as at 2019-11-29.
> Add config options

- ckanext/s3filestore/controller.py
Request object metadata before sending the redirect, so that we can detect missing files and fall back to the filesystem if configured.
> [QOL-5829] fix filesystem fallback, resolves #28

- ckanext/s3filestore/uploader.py
This matches the behaviour of the default filestore uploader
Resolves #30
> [QOL-5829] scan uploaded files to populate resource size field

- ckanext/s3filestore/uploader.py
This option is used by archiver as its storing a non-resource for cache purposes.
> preserve filename option to match iUploader interface update

- ckanext/s3filestore/uploader.py
We munge filenames (strip out characters except alphanumeric/dot/hyphen) when uploading, so we need to munge before trying to locate a file for download/deletion.
> Dql2 6 use consistent S3 filenames

- .gitignore
- README.rst
- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/uploader.py
ckan file store logic does not care about the filename provided by the user, it also stores
files without filenames nor filetype but as a uuid string in a resource folder.
S3 Plugin was built to store in a resource folder and the filename was used
If not provided it crashed, which was recently corrected.
Only problem is that people who use ckan have gotten use to being able to change
filenames not have the latest file served. Also with deep linking this also points to
old data which users do not like.
> Match ckan filestore logic

- .gitignore
- README.rst
- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/uploader.py
* Match ckan file store logic
ckan file store logic does not care about the filename provided by the user, it also stores
files without filenames nor filetype but as a uuid string in a resource folder.
S3 Plugin was built to store in a resource folder and the filename was used
If not provided it crashed, which was recently corrected.
Only problem is that people who use ckan have gotten use to being able to change
filenames and have the latest file served. Also with deep linking this also points to
old data which users do not like.
> Match ckan file store logic (#17)

- README.rst
- ckanext/s3filestore/controller.py
- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/uploader.py
- Use 'head' call to check for bucket presence instead of listing all buckets
- Reuse function instead of duplicating code
- Replace deprecated path-addressing style with virtual addressing
> Cleanup for QOL-7373

- ckanext/s3filestore/uploader.py
- requirements.txt
- We can only do it by globally monkey-patching the datetime module,
which introduces race conditions where different threads can get
references to different versions of the datetime functions.
> [QOL-7373] don't truncate signature timestamp

- ckanext/s3filestore/commands.py
- Don't try to match files with deleted resources
- Ignore validation errors since they're presumably pre-existing problems (validation rules may have changed since the resource was created)
> Make migration more robust

- ckanext/s3filestore/uploader.py
S3 metadata must only contain ASCII characters, so URL-encode the value before passing it through.
> QOL-8179 encode non-ASCII characters for S3 metadata

- ckanext/s3filestore/tests/test_uploader.py
- ckanext/s3filestore/uploader.py
- use string encode function instead of URL encoding
- handle multiple string types properly
> [QOL-8179] improve handling of non-ASCII characters for S3 metadata

- ckanext/s3filestore/tests/test_uploader.py
- ckanext/s3filestore/uploader.py
- This should ensure that we don't use an outdated cached copy after the resource changes,
by using a unique query string for each unique resource version.
> [QOL-8405] append ETag to unsigned URLs, #59

- ckanext/s3filestore/uploader.py
- ensure that string to be split is of the same type as the delimeter.
This is particularly relevant when retrieving strings from Redis cache,
which may return byte objects.
> [QOL-7545] update string type to fix github #62

- README.rst
- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/tasks.py
As IPackageController after_update is still in a transaction that has not been committed, we also need to remove any delays so we don't hang other processes wanting to touch the package this resource is in, s3 visibility update does not need the transaction to roll back
> Add after_update resource notify as a worker job instead (with fallback)

- ckanext/s3filestore/tests/test_uploader.py
- ckanext/s3filestore/uploader.py
- link resources may create a FileStorage object representing a zero-length binary stream, but they should not be treated as uploads
> [QOL-8518] handle link resources using placeholder empty FileStorage

- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/tasks.py
- ckanext/s3filestore/uploader.py
Look up package dict when we come to the enqueued job, not pass it into the queue. With the plugins currently installed, there is way too much metadata attached. Where there was an exception included by another plugin which is not stored in database which is then passed along
Looking at package_show, there is no way to remove other plugin injected data.
https://github.com/ckan/ckan/blob/526886d2c195bac8db555ff5477538d82ab2a2c2/ckan/logic/action/get.py#L937
https://www.data.qld.gov.au/api/action/package_show?id=b4a3f5d5-f3ac-4382-ae93-0c97293c8b69
Improvements we can make also.
Include on_failure function so it does not leave indefinite jobs
https://python-rq.org/docs/
```
* on_failure allows you to run a function after a job fails
* failure_ttl specifies how long failed jobs are kept …
```
> Reduce redis mem usage for enqueued items

- ckanext/s3filestore/plugin.py
- ckanext/s3filestore/tasks.py
- ckanext/s3filestore/tests/test_plugin.py
- use different arguments according to the CKAN version (and associated `rq` version)
- 'title' belongs at the top level, not within `kwargs` or `rq_kwargs`
- don't pass `None` queue names
- add testing to verify that arguments can be passed through without error
> QOL-8612 fix enqueuing of visibility updates

- ckanext/s3filestore/cli_commands.py
- Munge filenames when migrating, to match the behaviour when uploaded via the web interface
- Fix the disk location of files for single resources
- Handle 'auto' ACL values.
> QOL-8612 fix bugs in migration CLI

- ckanext/s3filestore/tests/test_uploader.py
- ckanext/s3filestore/uploader.py
- Don't assume that the package ID will be supplied as part of the uploaded resource
> [QOL-8943] look up package ID from resource ID

- .flake8
- .github/workflows/ci.yml
- ckanext/s3filestore/views/__init__.py
- scripts/build.sh
- scripts/init.sh
- scripts/test.sh
Allow our custom ckan version be tested against (which includes the iUploader changes to centralize download of files vs having it in a controller we need to override)
> Cicd upgrades

- README.rst
- Fix source install syntax
- Add a note on relationship with PyPI
> update README, GitHub issue #122

- .github/workflows/ci.yml
- ckanext/s3filestore/plugin.py
- scripts/test.sh
Add a test run on the latest upstream CKAN master, with success being optional (and tests currently fail), just so we have visibility.
> QOLDEV-1003 add optional testing of latest CKAN master
